
# DCIN Basic
NUM_DIES: 2  # Die数量

# DCIN Latency (ns)
D2D_AR_LATENCY: 20  # 地址读通道延迟
D2D_R_LATENCY: 20  # 读数据通道延迟
D2D_AW_LATENCY: 20  # 地址写通道延迟
D2D_W_LATENCY: 20  # 写数据通道延迟
D2D_B_LATENCY: 20  # 写响应通道延迟

# DCIN Bandwidth Limit (GB/s)
D2D_RN_BW_LIMIT: 192  # D2D RN带宽限制
D2D_SN_BW_LIMIT: 192  # D2D SN带宽限制
D2D_AXI_BANDWIDTH: 192  # AXI通道统一带宽限制

# DCIN Buffer Size
D2D_RN_RDB_SIZE: 512  # D2D RN读databuffer大小
D2D_RN_WDB_SIZE: 512  # D2D RN写databuffer大小
D2D_SN_RDB_SIZE: 512  # D2D SN读databuffer大小
D2D_SN_WDB_SIZE: 512  # D2D SN写databuffer大小
D2D_RN_R_TRACKER_OSTD: auto
D2D_RN_W_TRACKER_OSTD: auto
D2D_SN_R_TRACKER_OSTD: auto
D2D_SN_W_TRACKER_OSTD: auto

# Die拓扑配置
DIE_TOPOLOGIES:
  0: "2261_5x4"
  1: "2261_5x4"

# D2D连接配置
# 格式: [源Die, 源节点, 目标Die, 目标节点]
D2D_CONNECTIONS:
  - [0, 0, 1, 3]
  - [0, 1, 1, 2]
  - [0, 2, 1, 1]
  - [0, 3, 1, 0]
